apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce # means that persistence-storage can be used by a single node.
  resources:
    requests:
      storage: 2Gi